# Generated by Django 4.0.2 on 2022-02-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name')),
                ('body', models.CharField(db_index=True, max_length=14, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created DateTime')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
